#Install packages

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("clusterProfiler")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("org.Mm.eg.db")
BiocManager::install("GO.db")
BiocManager::install("DO.db")
BiocManager::install("DOSE")
BiocManager::install("enrichplot")
BiocManager::install("pathview")
BiocManager::install("PPInfer")
install.packages("shiny")
install.packages("shinydashboard")
install.packages('shinycssloaders')
install.packages("ggplot2")
install.packages("vroom")
install.packages("DT")
install.packages("utils")
install.packages("shinybusy")
install.packages("ggupset")
install.packages("phylobase")
BiocManager::install("GOSemSim")



library(clusterProfiler)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(ggplot2)
library(DOSE)
library(GO.db)
library(DO.db)
library(enrichplot)
library(DT)
library(utils)
library(vroom)
library(pathview)
library(shinybusy)
library(shiny)
library(shinydashboard)
library(pathview)
library(PPInfer)
library(ggupset)
library(phylobase)
library(shinycssloaders)
library(GOSemSim)